level = [
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
]