level = [
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"P              P                             P                                         P",
"P                P                           P                                         P",
"P                  P                       PP                               P          P",
"P       PPPPPP                                                                         P",
"P                                                                                      P",
"P                                                     PPPPPPP                          P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                         PPPPPP                       P",
"P                                                                                      P",
"P                   PPPPPPPPP                 P                                        P",
"P                                            P                                         P",
"P                                             P                                        P",
"P                                             P                                        P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                                                                      P",
"P                                             P                                        P",
"P                                             P                                        P",
"P                                             P                                P       P",
"P                                             P                                        P",
"P                                                                             P        P",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
]